### ISSUE TITLE
commands fail with memtier when DRAM only

### ISSUE THREAD

**Issue by akostadinov** [memkind/memkind#853] opened 2022-09-07 12:15 UTC
Hello, I'm trying to use memkind as a replacement of jemalloc when only DRAM would be used. i.e. just changing an environment variable to make allocator work properly depending on machine type?

But it doesn't work with `grep`.

```sh
$ LD_PRELOAD=/usr/lib64/libmemtier.so.0 MEMKIND_MEM_TIERS="KIND:DRAM,RATIO:1;POLICY:STATIC_RATIO" grep test <<< somestring
grep: memory exhausted
```

Would such use case be possible?

-- tbb-2020.3-9.fc35.x86_64

**Comment by PatKamin** [comment] 2022-09-09 08:37
Hi, that's correct that you can use libmemtier for replacing libc malloc() family of functions calls.

However, in this particular use case, the application fails because it relies on malloc() function returning a pointer in case the size passed is equal to zero. Note, that when using libmemtier, malloc() returns NULL in case the size passed is equal to zero. In general, according to malloc() specification, malloc() returns either NULL, or a unique pointer value that can later be successfully passed to free(). `grep` relies on the latter behavior of malloc(), whereas libmemtier (and memkind in general) sticks with the former.

I assume that you are currently using jemalloc with LD_PRELOAD for your applications and it works fine. Am I correct?

**Comment by akostadinov** [comment] 2022-09-09 11:59
Yes, `jemalloc` in `LD_PRELOAD` works fine.
```
LD_PRELOAD=/usr/lib64/libjemalloc.so.2 grep some <<< somestring
somestring
```

**Comment by PatKamin** [comment] 2022-09-26 06:43
As the behavior of `malloc()` that fails `grep` is an expected behavior, according to the memkind's documentation, changes to this function so that `memtier` in `LD_PRELOAD` could work with `grep` are not possible.

There might be even more differences in functions behavior between memkind API and jemalloc API, beside the one that affects `grep`. Because of that, there is no guarantee that every application ran with `memtier` in `LD_PRELOAD` will work as with `jemalloc` in `LD_PRELOAD`.

Is there something else I can help you with?

**Comment by akostadinov** [comment] 2022-09-26 09:10
If no changes are possible, I guess not. Thank you for the explanation.

**Comment by eggert** [comment] 2022-09-26 18:05
This is not a bug in grep. When grep is configured, it inspects the system malloc to see what malloc (0) does. If the system malloc (0) returns a null pointer, grep adjusts its build to use its own substitute malloc wrapper that treats malloc (0) as if it were malloc (1). If the system malloc (0) returns a unique non-null pointer, grep configure arranges for grep to call the system malloc directly, for efficiency.

If you plan to run grep with a particular malloc, you should configure grep using a compatible malloc. And this is not true only for grep; it's true for many other programs.

grep is not the only program that does this, and as things stand, if you blindly use memkind on a GNU/Linux system, you'll likely get similar results with many other programs. In that sense, this is a bug in memkind. For best results in this sort of testing, memkind malloc should be compatible with the system malloc, not merely compatible with POSIX. And since glibc malloc(0) returns NULL only when memory is exhausted, memkind malloc(0) should do the same on a GNU/Linux platform.

**Comment by akostadinov** [comment] 2022-09-27 07:04
@PatKamin , another interesting find is that in Fedora 36 the issue is as I described above. But in CentOS 8 stream, it works:
```
$ D_PRELOAD=libautohbw.so.0 AUTO_HBW_SIZE=10G AUTO_HBW_LOG=-1 MEMKIND_HBW_NODES=0 grep asd <<< asdsgddfsdfds
INFO: Setting log level to -1
	-HBW int call succeeded
asdsgddfsdfds
```

Can it be that memkind has different modes and it is the wrong one in Fedora?

**Comment by bratpiorka** [comment] 2022-09-27 08:08
@akostadinov No, memkind has a single malloc() implementation that works the same regardless of Linux distribution. But the idea described by @eggert is interesting and we will consider changing our implementation this way.

**Comment by PatKamin** [comment] 2022-11-09 10:11
Resolved with #856

**Closed by PatKamin** 2022-11-09 10:11 UTC

**Comment by akostadinov** [comment] 2022-11-09 14:03
@PatKamin , thank you! Which version will this be available with?

Also does it also work like this with `libautohbw`? I only see mentioned `libmemtier` in the pull request.

**Comment by PatKamin** [comment] 2022-11-09 14:22
This will be included in the next, possibly patch, release of memkind. This works only for libmemtier usage. This doesn't change the way libautohbw works. Usage of standard API of memkind without LD_PRELOAD is not changed, too.

**Comment by akostadinov** [comment] 2022-11-09 15:10
But `libautohbw` is also loaded through `LD_PRELOAD`? This would be inconsistent to have that lib behave differently.

**Comment by PatKamin** [comment] 2022-11-10 14:59
Yes, you're right. Updated libautohbw behavior to be consistent with libmemtier's behavior (with https://github.com/memkind/memkind/pull/858).

**Comment by akostadinov** [comment] 2023-10-23 19:20
Thank you for the help! When will 1.15 be released with these changes?

**Comment by PatKamin** [comment] 2023-10-24 06:36
For the next release plans, please reach out to current maintainers: https://github.com/memkind/memkind#contact-points
