### ISSUE TITLE
The best way to static link memkind in CMAKE Project

### ISSUE THREAD

**Issue by leslie-fang-intel** [memkind/memkind#698] opened 2021-08-14 00:00 UTC
Dear all, I have a projection with CMAKE, and I want to static link memkind.

Here is how I build memkind:
```
./autogen.sh
./configure --with-pic
make all -j
```

And the parts of my CmakeList
```
include_directories(${THIRD_PARTY_ROOT}/memkind/include)
# libmemkind
ExternalProject_Add(memkind
  SOURCE_DIR ${PROJECT_SOURCE_DIR}/third_party/memkind
  BUILD_IN_SOURCE 1
  CONFIGURE_COMMAND ""
  BUILD_COMMAND "${PROJECT_SOURCE_DIR}/third_party/memkind/build.sh"
  INSTALL_COMMAND ""
  )
target_link_libraries(${PLUGIN_NAME} PRIVATE ${THIRD_PARTY_ROOT}/memkind/.libs/libmemkind.a)
```

However, my projection will core dump here
https://github.com/memkind/memkind/blob/239dd058513614e6b0e79f93730840f6fce86e26/jemalloc/src/rtree.c#L205
But If I dynamic link `libmemkind.so`, this issue would not happen.
Any clues about the difference of `libmemkind.a` and `libmemkind.so`?

**Comment by leslie-fang-intel** [comment] 2021-08-14 00:01
Hi @Kkulakowski, Could you kindly help to take a look?

**Comment by bratpiorka** [comment] 2021-09-16 13:46
@leslie-fang-intel 
Did you resolve this issue? Is there anything else I can help or could we close it?

**Comment by leslie-fang-intel** [comment] 2021-09-16 14:15
Thanks you @bratpiorka. I will close it.

**Comment by tangleintel** [comment] 2022-06-26 18:58
> I compiled memkind **without "--with-pic"** option and linked it statically to my simple app using following flags: LIBS = -Wl,-Bstatic -lmemkind -Wl,-Bdynamic -ldl -lnuma -lpthread -ldaxctl -lhwloc and everything works fine.
> 
> Please try pass these flags to CMAKE. I also found this article with may be helpful: https://discourse.cmake.org/t/how-to-statically-link-external-library-by-target-link-libraries/1718
> 
> In case your issue still occurs, please share the minimal reproduce of this problem, so we can debug it.

Hi, @bratpiorka 
We can't compile **without "--with-pic"** option, cause our project will be compiled to a shared object other than an executable file. If we static link memkind into a shared object **without "--with-pic"** option, we will come across symbols relocation issue with gcc. The issue is similar like these [post1](https://stackoverflow.com/questions/7865059/why-does-gcc-force-pic-for-x64-shared-libs) [post2](https://github.com/open-source-parsers/jsoncpp/issues/708).

**Comment by tangleintel** [comment] 2022-06-26 19:01
@leslie-fang-intel Can you reopen this issue so that we can track it recently.

**Comment by maciekpac** [comment] 2022-08-11 15:22
@leslie-fang-intel I have a few questions:

1. Why do you build memkind outside of CMakeLists.txt ?
2. Are you aware that the ```./build.sh``` script calls ```./autogen.sh``` and ```./configure``` ? Moreover, it passes the arguments to these scripts, overriding the previous build - and making libs without the --with-pic flag...

I do not have access to your full CMakeLists.txt, but I suspect that either cmake does not build memkind and the hand-built version is used, or cmake builds the library and overrides it with incorrect flags ...

In any case, I have written some dummy program that uses --with-pic and I can't reproduce the issue...

Could you please provide info about the exact reproduction route ? If you can't share the code, maybe you could provide some generic, minimal code sample that crashes ?

**Comment by leslie-fang-intel** [comment] 2022-08-12 01:03
> @leslie-fang-intel I have a few questions:
> 
> 1. Why do you build memkind outside of CMakeLists.txt ?
> 2. Are you aware that the `./build.sh` script calls `./autogen.sh` and `./configure` ? Moreover, it passes the arguments to these scripts, overriding the previous build - and making libs without the --with-pic flag...
> 
> I do not have access to your full CMakeLists.txt, but I suspect that either cmake does not build memkind and the hand-built version is used, or cmake builds the library and overrides it with incorrect flags ...
> 
> In any case, I have written some dummy program that uses --with-pic and I can't reproduce the issue...
> 
> Could you please provide info about the exact reproduction route ? If you can't share the code, maybe you could provide some generic, minimal code sample that crashes ?

@tangleintel Could you help reply the questions from @maciekpac ?

**Comment by lukaszstolarczuk** [comment] 2023-01-26 15:24
This seems like a stale issue now. I'll allow myself to close it, but it there's any update on that, I'll reopen, and we can carry on with it.

**Closed by lukaszstolarczuk** 2023-01-26 15:24 UTC
